### PR TITLE
Math Magicians: Setup

### PR DESCRIPTION
**Pull request by dselasea**
In this pull request I

- Install Linters
- Install React
- Check Linter Errors
- Create Readme

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Selase, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure to remove Live demo link if app is not yet deployed.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by dselasea** [comment]
Hi @rloterh 👋🏾  Kindly let me know why my pull request is not valid. I don't understand your feedback. Also, I did not provide any link to a demo. The link says N/A. I would appreciate your clarity since I do not understand your feedback.

**Comment by rloterh** [comment]
Please check your ReadMe carefully:
image

I can notice that you've indicated it's not available. However, we want you to **remove the link entirely if the project is not yet deployed.** Please note that this criterion is required in order for your project to be reviewed.

Cheers! 😃

**Review by nahnahdev — CHANGES_REQUESTED** [review]
## Project Status: CHANGES REQUIRED :recycle: 
Hi @dselasea , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- App created with `create react app` :heavy_check_mark: 
- No linter errors :heavy_check_mark: 
- No console errors :heavy_check_mark: 

## Required Changes ♻️
- As the previous reviewer mentioned, the link in your README under your Live Demo section currently leads to an error page. Kindly remove the link and leave only `N/A` so you don't mislead visitors on your page :+1: 
- Your Live Demo Link
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by prolajumokeoni — APPROVED** [review]
Hi @dselasea 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
  - All changes requested have been implemented 👍🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
